### ISSUE TITLE
UMA BOSTA

### ISSUE THREAD

**Issue by ThiagoLira** [HomeSkyLtd/controller#1]
Usei isso e prendi meu penis num ventilador, instrucoes nao foram claras

**Comment by adrianodennanni** [comment]
Também prendi o meu, como proceder?????

**Comment by ricardobg** [comment]
Fixed on 0.1.0

**Comment by ThiagoLira** [comment]
thanks man

**Comment by ricardobg** [comment]
Sorry

**Comment by ThiagoLira** [comment]
Its okay, it's already growing again
